### ISSUE TITLE
Activate it on a bone of a character and not on the whole character?

### ISSUE THREAD

**Issue by DanielDanielDanielD** [robinwood3d/UE5RuntimeTransformGizmo#3]
Hi, thanks for the project you are sharing, this is exactly what I was looking for for my project.
I have a question about activating the Gizmo, is it possible to activate it on a bone of a character and not on the whole character?

**Comment by robinwood3d** [comment]
I remember the activate function accept a transform type parameter, may be you can get the bone's transform and the pass to the activate function.

Unreal Engine has transform gizmo feature built in. Check these post:
https://www.gradientspace.com/tutorials/2022/6/1/the-interactive-tools-framework-in-ue5

https://www.gradientspace.com/tutorials/2021/01/19/the-interactive-tools-framework-in-ue426

获取Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
发件人: Daniel Coryat ***@***.***>
发送时间: 2022年12月5日星期一 下午6:25
收件人: robinwood3d/UE4RuntimeTransformGizmo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [robinwood3d/UE4RuntimeTransformGizmo] Activate it on a bone of a character and not on the whole character? (Issue #3)


Hi, thanks for the project you are sharing, this is exactly what I was looking for for my project.
I have a question about activating the Gizmo, is it possible to activate it on a bone of a character and not on the whole character?

―

**Comment by DanielDanielDanielD** [comment]
This is great content, I will test it out. Thank you
